In [3]:
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
print(np.sum(a))
print(np.sum(a,axis=0))


3
3


In [4]:
#stacing of arrays
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,8])
print(a.dot(b))

64


In [5]:
print(a)

[1 2 3 4]


In [6]:
b=b**2
print(b)

[16 25 36 64]


In [9]:
a=np.stack((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [16, 25, 36, 64]])

In [12]:
#reshape a numpy array 
a=a.reshape((5,2))
print(a)

ValueError: ignored