In [7]:
import numpy as np
a=np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [14]:
np.seed(1)
np.random.shuffle(a)
print(a)

AttributeError: ignored

In [13]:
#returns values froma a standard normal distribution
a=np.random.rand(2,3)
print(a)
a=np.random.randint(5,10,3)
print(a)
element=np.random.choice([1,4,3,21,11,23])
print(element)



[[0.32141321 0.96872915 0.54405063]
 [0.17474084 0.96076467 0.14535877]]
[9 7 6]
23
