In [2]:
import numpy as np
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#specify axis for the direction in case of multidimensional
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [5]:
c=np.array([1,2,3,4])
print(np.median(c))

2.5


In [3]:
#mean,average
b=np.array([1,2,3,4])
print(np.mean(b))
print(np.mean(a,axis=0))

2.5


In [7]:
c=np.array([1,5,4,2,0])
print(np.median(c))
print(np.mean(c))
w=np.array([1,2,3,4,5])
#weighted average
print(np.average(c,weights=w))
#standard deviation
dev=np.std(c)
print(dev)

2.0
2.4
2.066666666666667
1.854723699099141
